# Generated by Django 4.2.8 on 2024-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search_url', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('keyword', models.CharField(max_length=500, null=True)),
                ('category_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_charge', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
