name: Django CD

on:
  push:
    branches:
      - develop


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set environment variables for MySQL
      run: |
        mkdir -p db
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > db/.env
        echo "MYSQL_ROOT_USER=${{ secrets.MYSQL_ROOT_USER }}" >> db/.env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> db/.env
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> db/.env

    - name: Set environment variables for Django
      run: |
        mkdir -p django_backend
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" > django_backend/.env
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> django_backend/.env
        echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" >> django_backend/.env
        echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> django_backend/.env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> django_backend/.env

    - name: Build and push Docker images
      run: |
        echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
        docker-compose build --progress=plain
        docker-compose push

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/backend
          git pull
          docker-compose pull
          docker-compose up -d
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
